### ISSUE TITLE
Example with global data in spherical projection

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista-xarray#17]
https://www.ncei.noaa.gov/products/optimum-interpolation-sst

[oisst-avhrr-v02r01.19810901.nc.zip](https://github.com/pyvista/pyvista-xarray/files/9007268/oisst-avhrr-v02r01.19810901.nc.zip)

```py
import xarray
ds = xarray.open_dataset('oisst-avhrr-v02r01.19810901.nc')
ds.err.plot()
```
![download](https://user-images.githubusercontent.com/22067021/176353011-cec4735d-0c83-4681-8780-bfe1334aade5.png)

**Comment by banesullivan** [comment]
The tricky part is performing the 3D coordinate transform - this can get very complicated very quickly and this library's goal is not to perform coordinate transforms.

I'm going to see what I can do to use existing tools to do this.

**Comment by banesullivan** [comment]
had a great chat with @bjlittle about using `geovista` to this end - he's created some fantastic functionality in that library to handle all of the coordinate transforms, and I think with a little bit of work, we can leverage `geovista`'s transformer/bridge to handle the 3D reprojections here.

ref https://geovista.readthedocs.io/en/latest/ and https://github.com/bjlittle/geovista

We will follow up in a few weeks

**Comment by bjlittle** [comment]
@banesullivan I've made some time to spin back up and show some love to `geovista`.

I've bolstered the `README.md` in the short-term until it get space to fully bootstrap the docs for the 0.1.0 release. 

However, you'll be glad to hear that I've also made **most** of the `geovista/examples` self-contained, so that they are agnostic of `SciTools/iris` and automatically download and cache the required `geovista` sample data. I just have a couple of examples still to self-contain, so I'll let you know when I've done that.

There are still a few major wrinkles to iron out prior to the 0.1.0 release, but I'm also keen to start thinking about providing support for rectilinear/uniform/structured grids to underpin the `pyvista-xarray` use case.

**Comment by bjlittle** [comment]
@banesullivan BTW the above NOAA/NCEI OISST AVHRR dataset looks like this:
![image](https://user-images.githubusercontent.com/2051656/180887602-e1c71e32-8c0f-4cee-a587-ae9d226a571c.png)

Which looks rather lush. I also added the dataset as a GeoVista pantry sample, and highlighted it on the [README](https://github.com/bjlittle/geovista#oisst-avhrr) and also created an example, see [example_from_1d__oisst.py](https://github.com/bjlittle/geovista/blob/main/examples/example_from_1d__oisst.py).

**Comment by RichardScottOZ** [comment]
This looks excellent.

**Comment by banesullivan** [comment]
I'm going to mark this issue complete with examples in the `examples/` directory now that show how to use PyVista-Xarray with GeoVista. However, this work is not fully complete until the following Pull Requests merge:

- https://github.com/pyvista/pyvista/pull/3318
- https://github.com/bjlittle/geovista/pull/127
